// src/components/admin/WorkersStatusDashboard.tsx
import React, { useState, useEffect } from "react";

interface WorkerStatus {
  name: string;
  status: "online" | "offline" | "partial" | "maintenance";
  cpu: number | null;
  ram: number | null;
  requests: number;
  responseMs: number | null;
  lastCheck: string;
  uptime: string;
  errors: number;
  url?: string;
}

interface WorkersStatusDashboardProps {
  className?: string;
}

const statusColor = (status: string) => {
  switch (status) {
    case "online":
      return "text-emerald-400 bg-emerald-900/30";
    case "partial":
      return "text-yellow-400 bg-yellow-900/30";
    case "offline":
      return "text-red-400 bg-red-900/30";
    case "maintenance":
      return "text-blue-400 bg-blue-900/30";
    default:
      return "text-gray-400 bg-gray-900/30";
  }
};

const statusIcon = (status: string) => {
  switch (status) {
    case "online":
      return "●";
    case "partial":
      return "◐";
    case "offline":
      return "○";
    case "maintenance":
      return "◇";
    default:
      return "?";
  }
};

export default function WorkersStatusDashboard({
  className = "",
}: WorkersStatusDashboardProps) {
  const [workers, setWorkers] = useState<WorkerStatus[]>([]);
  const [loading, setLoading] = useState(false);
  const [lastRefresh, setLastRefresh] = useState<string>("");
  const [autoRefresh, setAutoRefresh] = useState(false);
  const [refreshInterval, setRefreshInterval] = useState<NodeJS.Timeout | null>(
    null
  );

  const fetchWorkersStatus = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/admin/workers-status");
      if (response.ok) {
        const data = (await response.json()) as any;
        setWorkers(data.workers || []);
        setLastRefresh(new Date().toLocaleTimeString());
      } else {
        console.error("Failed to fetch workers status");
        // Fallback mock data for demo
        setWorkers([
          {
            name: "AI Bot Worker",
            status: "online",
            cpu: 32,
            ram: 79,
            requests: 150,
            responseMs: 140,
            lastCheck: new Date().toISOString(),
            uptime: "99.8%",
            errors: 0,
            url: "/api/ai-bot",
          },
          {
            name: "Generate Image",
            status: "online",
            cpu: 67,
            ram: 89,
            requests: 89,
            responseMs: 320,
            lastCheck: new Date().toISOString(),
            uptime: "99.9%",
            errors: 2,
            url: "/api/generate-image",
          },
          {
            name: "FAQ Generator",
            status: "partial",
            cpu: 45,
            ram: 39,
            requests: 69,
            responseMs: 200,
            lastCheck: new Date().toISOString(),
            uptime: "97.2%",
            errors: 5,
            url: "/api/faq-generator",
          },
          {
            name: "Voice Avatar",
            status: "offline",
            cpu: null,
            ram: null,
            requests: 0,
            responseMs: null,
            lastCheck: new Date(Date.now() - 300000).toISOString(),
            uptime: "0%",
            errors: 12,
            url: "/api/voice-avatar",
          },
          {
            name: "Marketing Content",
            status: "online",
            cpu: 28,
            ram: 56,
            requests: 234,
            responseMs: 95,
            lastCheck: new Date().toISOString(),
            uptime: "99.5%",
            errors: 1,
            url: "/api/generate-marketing-content",
          },
        ]);
        setLastRefresh(new Date().toLocaleTimeString());
      }
    } catch (error) {
      console.error("Error fetching workers status:", error);
    } finally {
      setLoading(false);
    }
  };

  const testWorker = async (worker: WorkerStatus) => {
    if (!worker.url) return;

    try {
      const response = await fetch(worker.url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ test: true }),
      });

      const updatedWorkers = workers.map((w) =>
        w.name === worker.name
          ? {
              ...w,
              status: response.ok ? ("online" as const) : ("offline" as const),
              lastCheck: new Date().toISOString(),
            }
          : w
      );
      setWorkers(updatedWorkers);
    } catch (error) {
      const updatedWorkers = workers.map((w) =>
        w.name === worker.name
          ? {
              ...w,
              status: "offline" as const,
              lastCheck: new Date().toISOString(),
            }
          : w
      );
      setWorkers(updatedWorkers);
    }
  };

  const toggleAutoRefresh = () => {
    if (autoRefresh && refreshInterval) {
      clearInterval(refreshInterval);
      setRefreshInterval(null);
      setAutoRefresh(false);
    } else {
      const interval = setInterval(fetchWorkersStatus, 30000); // 30 seconds
      setRefreshInterval(interval);
      setAutoRefresh(true);
    }
  };

  useEffect(() => {
    fetchWorkersStatus();
    return () => {
      if (refreshInterval) {
        clearInterval(refreshInterval);
      }
    };
  }, []);

  const onlineWorkers = workers.filter((w) => w.status === "online").length;
  const totalWorkers = workers.length;
  const avgResponseTime =
    workers
      .filter((w) => w.responseMs !== null)
      .reduce((sum, w) => sum + (w.responseMs || 0), 0) /
      workers.filter((w) => w.responseMs !== null).length || 0;

  return (
    <div
      className={`bg-black/90 backdrop-blur-sm rounded-xl border border-cyan-500/30 p-6 ${className}`}
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center space-x-3">
          <h2 className="text-2xl font-bold text-cyan-400 tracking-wider">
            WORKERS STATUS
          </h2>
          <div className="px-3 py-1 bg-cyan-900/50 rounded-full text-cyan-300 text-sm font-mono">
            {onlineWorkers}/{totalWorkers} ONLINE
          </div>
        </div>
        <div className="flex items-center space-x-2 text-sm text-cyan-300">
          <span>Last refresh: {lastRefresh}</span>
          {autoRefresh && (
            <span className="text-emerald-400 animate-pulse">●</span>
          )}
        </div>
      </div>

      {/* Stats Overview */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
        <div className="bg-gray-900/50 rounded-lg p-4 border border-cyan-800/30">
          <div className="text-cyan-400 text-sm uppercase tracking-wide">
            Uptime
          </div>
          <div className="text-2xl font-bold text-white">
            {((onlineWorkers / totalWorkers) * 100).toFixed(1)}%
          </div>
        </div>
        <div className="bg-gray-900/50 rounded-lg p-4 border border-cyan-800/30">
          <div className="text-cyan-400 text-sm uppercase tracking-wide">
            Avg Response
          </div>
          <div className="text-2xl font-bold text-white">
            {avgResponseTime.toFixed(0)}ms
          </div>
        </div>
        <div className="bg-gray-900/50 rounded-lg p-4 border border-cyan-800/30">
          <div className="text-cyan-400 text-sm uppercase tracking-wide">
            Total Requests
          </div>
          <div className="text-2xl font-bold text-white">
            {workers.reduce((sum, w) => sum + w.requests, 0)}
          </div>
        </div>
        <div className="bg-gray-900/50 rounded-lg p-4 border border-cyan-800/30">
          <div className="text-cyan-400 text-sm uppercase tracking-wide">
            Total Errors
          </div>
          <div className="text-2xl font-bold text-white">
            {workers.reduce((sum, w) => sum + w.errors, 0)}
          </div>
        </div>
      </div>

      {/* Control Buttons */}
      <div className="flex flex-wrap gap-2 mb-6">
        <button
          onClick={fetchWorkersStatus}
          disabled={loading}
          className="px-4 py-2 bg-cyan-800/70 hover:bg-cyan-700 text-cyan-100 rounded-md transition-colors duration-200 disabled:opacity-50 font-mono text-sm"
        >
          {loading ? "CHECKING..." : "HEALTH CHECK"}
        </button>
        <button
          onClick={toggleAutoRefresh}
          className={`px-4 py-2 rounded-md transition-colors duration-200 font-mono text-sm ${
            autoRefresh
              ? "bg-emerald-800/70 hover:bg-emerald-700 text-emerald-100"
              : "bg-gray-800/70 hover:bg-gray-700 text-gray-100"
          }`}
        >
          {autoRefresh ? "STOP AUTO" : "AUTO REFRESH"}
        </button>
        <button
          onClick={() => workers.forEach(testWorker)}
          className="px-4 py-2 bg-yellow-800/70 hover:bg-yellow-700 text-yellow-100 rounded-md transition-colors duration-200 font-mono text-sm"
        >
          TEST ALL
        </button>
      </div>

      {/* Workers Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-cyan-800/50">
              <th className="text-left py-3 px-2 text-cyan-400 font-mono uppercase tracking-wide">
                Worker
              </th>
              <th className="text-left py-3 px-2 text-cyan-400 font-mono uppercase tracking-wide">
                Status
              </th>
              <th className="text-left py-3 px-2 text-cyan-400 font-mono uppercase tracking-wide">
                CPU
              </th>
              <th className="text-left py-3 px-2 text-cyan-400 font-mono uppercase tracking-wide">
                RAM
              </th>
              <th className="text-left py-3 px-2 text-cyan-400 font-mono uppercase tracking-wide">
                Requests
              </th>
              <th className="text-left py-3 px-2 text-cyan-400 font-mono uppercase tracking-wide">
                Response
              </th>
              <th className="text-left py-3 px-2 text-cyan-400 font-mono uppercase tracking-wide">
                Uptime
              </th>
              <th className="text-left py-3 px-2 text-cyan-400 font-mono uppercase tracking-wide">
                Errors
              </th>
              <th className="text-left py-3 px-2 text-cyan-400 font-mono uppercase tracking-wide">
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            {workers.map((worker, index) => (
              <tr
                key={index}
                className="border-b border-gray-800/30 hover:bg-cyan-900/10 transition-colors"
              >
                <td className="py-3 px-2">
                  <div className="font-mono text-white">{worker.name}</div>
                  <div className="text-xs text-gray-400">{worker.url}</div>
                </td>
                <td className="py-3 px-2">
                  <span
                    className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-mono ${statusColor(
                      worker.status
                    )}`}
                  >
                    <span className="mr-1">{statusIcon(worker.status)}</span>
                    {worker.status.toUpperCase()}
                  </span>
                </td>
                <td className="py-3 px-2 font-mono text-white">
                  {worker.cpu !== null ? `${worker.cpu}%` : "-"}
                </td>
                <td className="py-3 px-2 font-mono text-white">
                  {worker.ram !== null ? `${worker.ram}%` : "-"}
                </td>
                <td className="py-3 px-2 font-mono text-white">
                  {worker.requests.toLocaleString()}
                </td>
                <td className="py-3 px-2 font-mono text-white">
                  {worker.responseMs !== null ? `${worker.responseMs}ms` : "-"}
                </td>
                <td className="py-3 px-2 font-mono text-white">
                  {worker.uptime}
                </td>
                <td className="py-3 px-2 font-mono text-white">
                  <span
                    className={
                      worker.errors > 0 ? "text-red-400" : "text-emerald-400"
                    }
                  >
                    {worker.errors}
                  </span>
                </td>
                <td className="py-3 px-2">
                  <button
                    onClick={() => testWorker(worker)}
                    className="text-xs px-2 py-1 bg-blue-800/70 hover:bg-blue-700 text-blue-100 rounded font-mono transition-colors"
                  >
                    TEST
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {workers.length === 0 && !loading && (
        <div className="text-center py-8 text-gray-400">
          No workers found. Click "HEALTH CHECK" to scan for workers.
        </div>
      )}
    </div>
  );
}

// src/components/WorkersStatusDashboard.svelte
<script>
  import { onMount } from "svelte";
  import WorkersStatusChart from "./WorkersStatusChart.svelte";

  let workers = [];
  let metrics = {};
  let loading = false;
  let showChart = false;
  let error = null;
  let autoRefresh = true;
  let refreshInterval;

  // Status color mapping
  function getStatusColor(status) {
    switch (status) {
      case "online":
        return "text-green-400";
      case "partial":
        return "text-yellow-400";
      case "offline":
        return "text-red-400";
      default:
        return "text-gray-400";
    }
  }

  function getStatusDot(status) {
    switch (status) {
      case "online":
        return "bg-green-400";
      case "partial":
        return "bg-yellow-400";
      case "offline":
        return "bg-red-400";
      default:
        return "bg-gray-400";
    }
  }

  function getStatusBg(status) {
    switch (status) {
      case "online":
        return "bg-green-500/20 border-green-500/30";
      case "partial":
        return "bg-yellow-500/20 border-yellow-500/30";
      case "offline":
        return "bg-red-500/20 border-red-500/30";
      default:
        return "bg-gray-500/20 border-gray-500/30";
    }
  }

  async function fetchWorkersStatus() {
    loading = true;
    error = null;

    try {
      console.log("🔄 Fetching workers status...");
      const response = await fetch("/api/workers-status");

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      const data = await response.json();

      if (data.success) {
        workers = data.workers;
        metrics = data.metrics;
        console.log("✅ Workers status fetched successfully", {
          workers: workers.length,
          metrics,
        });
      } else {
        throw new Error(data.error || "Failed to fetch workers status");
      }
    } catch (err) {
      error = err.message;
      console.error("❌ Error fetching workers status:", err);
    } finally {
      loading = false;
    }
  }

  function toggleAutoRefresh() {
    autoRefresh = !autoRefresh;
    if (autoRefresh) {
      refreshInterval = setInterval(fetchWorkersStatus, 30000); // Refresh every 30 seconds
    } else {
      clearInterval(refreshInterval);
    }
  }

  function formatTime(isoString) {
    return new Date(isoString).toLocaleTimeString("pl-PL");
  }

  function formatUptime(uptime) {
    return uptime || "0%";
  }

  onMount(() => {
    fetchWorkersStatus();
    if (autoRefresh) {
      refreshInterval = setInterval(fetchWorkersStatus, 30000);
    }

    return () => {
      if (refreshInterval) clearInterval(refreshInterval);
    };
  });
</script>

<div class="w-full bg-[#111111] border border-[#333333] glass-effect p-6">
  <!-- Header -->
  <div class="flex items-center justify-between mb-6">
    <div>
      <h2
        class="text-2xl font-bold text-[#00ffff] font-['Neuropol'] uppercase tracking-wider"
      >
        🔧 Status Workerów
      </h2>
      <p class="text-[#a0a0a0] font-['Kenyan_Coffee'] mt-1">
        Zaawansowany monitoring systemu AI funkcji w czasie rzeczywistym
      </p>
    </div>

    <div class="flex items-center gap-3">
      <button
        on:click={toggleAutoRefresh}
        class="px-3 py-1 text-xs font-['Neuropol'] uppercase border transition-all duration-300"
        class:auto-refresh-active={autoRefresh}
        class:auto-refresh-inactive={!autoRefresh}
      >
        Auto: {autoRefresh ? "ON" : "OFF"}
      </button>

      {#if metrics.lastUpdate}
        <span class="text-xs text-[#666666] font-['Kenyan_Coffee']">
          Last: {formatTime(metrics.lastUpdate)}
        </span>
      {/if}
    </div>
  </div>

  <!-- System Overview -->
  {#if metrics.totalWorkers}
    <div class="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
      <div class="p-3 bg-[#0a0a0a] border border-[#333333] text-center">
        <div class="text-lg font-bold text-[#00ffff] font-['Neuropol']">
          {metrics.onlineWorkers}
        </div>
        <div class="text-xs text-[#a0a0a0] uppercase">Online</div>
      </div>
      <div class="p-3 bg-[#0a0a0a] border border-[#333333] text-center">
        <div class="text-lg font-bold text-yellow-400 font-['Neuropol']">
          {metrics.partialWorkers}
        </div>
        <div class="text-xs text-[#a0a0a0] uppercase">Partial</div>
      </div>
      <div class="p-3 bg-[#0a0a0a] border border-[#333333] text-center">
        <div class="text-lg font-bold text-red-400 font-['Neuropol']">
          {metrics.offlineWorkers}
        </div>
        <div class="text-xs text-[#a0a0a0] uppercase">Offline</div>
      </div>
      <div class="p-3 bg-[#0a0a0a] border border-[#333333] text-center">
        <div class="text-lg font-bold text-[#00ffff] font-['Neuropol']">
          {metrics.totalRequests}
        </div>
        <div class="text-xs text-[#a0a0a0] uppercase">Total Req/min</div>
      </div>
      <div class="p-3 bg-[#0a0a0a] border border-[#333333] text-center">
        <div class="text-lg font-bold text-[#00ffff] font-['Neuropol']">
          {metrics.avgResponseTime}ms
        </div>
        <div class="text-xs text-[#a0a0a0] uppercase">Avg Response</div>
      </div>
    </div>
  {/if}

  <!-- System Health Bar -->
  {#if metrics.systemHealth !== undefined}
    <div class="mb-6">
      <div class="flex justify-between text-sm mb-2">
        <span class="text-[#a0a0a0] font-['Kenyan_Coffee']"
          >Ogólny Stan Systemu</span
        >
        <span class="text-[#00ffff] font-['Neuropol']"
          >{Math.round(metrics.systemHealth)}%</span
        >
      </div>
      <div class="w-full bg-[#333333] h-2 border border-[#555555]">
        <div
          class="h-full transition-all duration-500"
          class:bg-green-500={metrics.systemHealth >= 80}
          class:bg-yellow-500={metrics.systemHealth >= 50 &&
            metrics.systemHealth < 80}
          class:bg-red-500={metrics.systemHealth < 50}
          style="width: {metrics.systemHealth}%"
        ></div>
      </div>
    </div>
  {/if}
  <!-- Control Buttons -->
  <div class="flex flex-wrap gap-3 mb-6">
    <button
      on:click={fetchWorkersStatus}
      disabled={loading}
      class="px-4 py-2 bg-[#00ffff]/10 border border-[#00ffff]/30 text-[#00ffff] hover:bg-[#00ffff]/20 transition-all duration-300 font-['Neuropol'] uppercase text-sm disabled:opacity-50"
    >
      {loading ? "Sprawdzanie..." : "🔍 Health Check"}
    </button>

    <button
      on:click={() => (showChart = !showChart)}
      class="px-4 py-2 bg-[#00ffff]/10 border border-[#00ffff]/30 text-[#00ffff] hover:bg-[#00ffff]/20 transition-all duration-300 font-['Neuropol'] uppercase text-sm"
    >
      {showChart ? "Ukryj Monitoring" : "📊 Pokaż Monitoring"}
    </button>

    <button
      on:click={fetchWorkersStatus}
      class="px-4 py-2 bg-[#00ffff]/10 border border-[#00ffff]/30 text-[#00ffff] hover:bg-[#00ffff]/20 transition-all duration-300 font-['Neuropol'] uppercase text-sm"
    >
      🔧 API Status
    </button>
  </div>

  <!-- Error Display -->
  {#if error}
    <div class="mb-4 p-3 bg-red-500/10 border border-red-500/30 text-red-400">
      <div class="font-['Neuropol'] uppercase text-sm">Error</div>
      <div class="font-['Kenyan_Coffee'] text-sm">{error}</div>
    </div>
  {/if}

  <!-- Workers Status Summary -->
  <div class="mb-4">
    {#if loading}
      <span class="text-[#a0a0a0] font-['Kenyan_Coffee']"
        >Trwa sprawdzanie statusu workerów...</span
      >
    {:else if workers.length > 0}
      <span class="text-[#e0e0e0] font-['Kenyan_Coffee']">
        <span class="text-green-400">{metrics.onlineWorkers}</span> /
        <span class="text-[#00ffff]">{metrics.totalWorkers}</span> workerów
        online
        {#if metrics.systemHealth}
          - System Health: <span class="text-[#00ffff]"
            >{Math.round(metrics.systemHealth)}%</span
          >
        {/if}
      </span>
    {:else}
      <span class="text-[#a0a0a0] font-['Kenyan_Coffee']"
        >Brak danych o workerach</span
      >
    {/if}
  </div>

  <!-- Workers Table -->
  <div class="overflow-x-auto border border-[#333333]">
    <table class="min-w-full bg-[#0a0a0a]">
      <thead>
        <tr class="border-b border-[#333333]">
          <th
            class="px-4 py-3 text-left text-[#00ffff] font-['Neuropol'] uppercase text-sm"
            >Nazwa Workera</th
          >
          <th
            class="px-4 py-3 text-left text-[#00ffff] font-['Neuropol'] uppercase text-sm"
            >Status</th
          >
          <th
            class="px-4 py-3 text-left text-[#00ffff] font-['Neuropol'] uppercase text-sm"
            >CPU</th
          >
          <th
            class="px-4 py-3 text-left text-[#00ffff] font-['Neuropol'] uppercase text-sm"
            >RAM</th
          >
          <th
            class="px-4 py-3 text-left text-[#00ffff] font-['Neuropol'] uppercase text-sm"
            >Req/min</th
          >
          <th
            class="px-4 py-3 text-left text-[#00ffff] font-['Neuropol'] uppercase text-sm"
            >Response</th
          >
          <th
            class="px-4 py-3 text-left text-[#00ffff] font-['Neuropol'] uppercase text-sm"
            >Uptime</th
          >
          <th
            class="px-4 py-3 text-left text-[#00ffff] font-['Neuropol'] uppercase text-sm"
            >Last Check</th
          >
        </tr>
      </thead>
      <tbody>
        {#each workers as worker, i}
          <tr
            class="border-b border-[#333333]/50 hover:bg-[#111111] transition-colors duration-200"
          >
            <td class="px-4 py-3">
              <div class="text-[#e0e0e0] font-['Kenyan_Coffee'] font-medium">
                {worker.name}
              </div>
              <div class="text-xs text-[#666666] font-['Kenyan_Coffee']">
                {worker.endpoint}
              </div>
            </td>
            <td class="px-4 py-3">
              <span
                class="px-2 py-1 text-xs font-['Neuropol'] uppercase border {getStatusBg(
                  worker.status
                )} {getStatusColor(worker.status)}"
              >
                {worker.status}
              </span>
            </td>
            <td class="px-4 py-3 text-[#e0e0e0] font-['Kenyan_Coffee']">
              {worker.cpu !== null ? worker.cpu + "%" : "-"}
            </td>
            <td class="px-4 py-3 text-[#e0e0e0] font-['Kenyan_Coffee']">
              {worker.ram !== null ? worker.ram + "%" : "-"}
            </td>
            <td class="px-4 py-3 text-[#e0e0e0] font-['Kenyan_Coffee']">
              {worker.requests || 0}
            </td>
            <td class="px-4 py-3 text-[#e0e0e0] font-['Kenyan_Coffee']">
              {worker.responseMs !== null ? worker.responseMs + "ms" : "-"}
            </td>
            <td class="px-4 py-3 text-[#e0e0e0] font-['Kenyan_Coffee']">
              {formatUptime(worker.uptime)}
            </td>
            <td class="px-4 py-3 text-[#a0a0a0] font-['Kenyan_Coffee'] text-sm">
              {worker.lastCheck ? formatTime(worker.lastCheck) : "-"}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>

  <!-- Action Buttons -->
  <div class="mt-6 flex flex-col gap-3">
    <button
      on:click={fetchWorkersStatus}
      disabled={loading}
      class="w-full p-3 bg-[#00ffff]/10 border border-[#00ffff]/30 text-[#00ffff] hover:bg-[#00ffff]/20 transition-all duration-300 font-['Neuropol'] uppercase tracking-wide disabled:opacity-50"
    >
      {loading ? "Sprawdzanie..." : "Sprawdź Wszystkie Workery"}
    </button>

    <button
      on:click={() => (showChart = !showChart)}
      class="w-full p-3 bg-[#00ffff]/10 border border-[#00ffff]/30 text-[#00ffff] hover:bg-[#00ffff]/20 transition-all duration-300 font-['Neuropol'] uppercase tracking-wide"
    >
      {showChart ? "Ukryj" : "Pokaż"} Szczegółowy Monitor
    </button>
  </div>

  <!-- Chart Modal/Section -->
  {#if showChart && workers.length > 0}
    <WorkersStatusChart
      {workers}
      {metrics}
      onClose={() => (showChart = false)}
    />
  {/if}
</div>

<style>
  .glass-effect {
    backdrop-filter: blur(10px);
    background: rgba(17, 17, 17, 0.8);
  }

  .auto-refresh-active {
    background-color: rgba(0, 255, 255, 0.2);
    border-color: rgba(0, 255, 255, 0.3);
    color: #00ffff;
  }

  .auto-refresh-inactive {
    background-color: rgba(51, 51, 51, 0.2);
    border-color: rgba(102, 102, 102, 0.3);
    color: #a0a0a0;
  }
</style>
